"""add email templates to rules

Revision ID: 252e73e4bd84
Revises: 420528b0cb1a
Create Date: 2026-05-03 03:24:54.387536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252e73e4bd84'
down_revision: Union[str, None] = '420528b0cb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_rules', sa.Column('subject_template', sa.String(length=255), nullable=True))
    op.add_column('reminder_rules', sa.Column('body_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder_rules', 'body_template')
    op.drop_column('reminder_rules', 'subject_template')
    # ### end Alembic commands ###
